### ISSUE TITLE
Getting a setsockopt(2) Warning

### ISSUE THREAD

**Issue by ngzax** [launchdarkly/ruby-eventsource#30]
Hi. I am hoping to get some guidance on what to do with the following error:

```
WARN -- ld-eventsource: Unexpected error from event source: #<Faraday::ConnectionFailed wrapped=#<Errno::EINVAL: Invalid argument - setsockopt(2)>>
```

How would I proceed to debug what is going on with this? Thanks.

**Comment by eli-darkly** [comment]
There's not much to go on here. For any problem report, it's common to provide some background information such as:

* what version of this library you are using
* what Ruby version, on what OS
* what other dependencies does your application have (for instance, it looks like Faraday is involved here in some way - that is not something ruby-eventsource itself normally uses)
* does this happen all the time or only under certain circumstances? is it reproducible?

**Comment by ngzax** [comment]
Thanks for you prompt reply. Sorry for the lack of info.

* ld-eventsource 2.2.0
* ruby 2.7.4
* yeah, i am using Faraday (also 2.2.0) for general HTTP ops
* it is reproducible, i can work to isolate a small bit of code that does it.

I am working with an external app that communicates via SSE and this is my first time using it. It is quite possible that it is this app that is doing something wrong and ld-eventsource is fine, that is why I was hoping for some general advice on debugging SSE application rather than assuming that this is a problem with this lib.

Thanks again for your help.

**Comment by eli-darkly** [comment]
Unfortunately I can't think of any general advice in terms of SSE, and I'm not sure how relevant that would be. I mean, it seems pretty clear that this is _not_ an error related to parsing of the event stream, or anything else that is specific to the SSE protocol. The error has something to do with the basic operation of making an HTTP request; it is complaining that it can't open a connection, due to some kind of problem with the low-level OS operations for that. So I think this is less a case of "debugging an SSE application"— more like "debugging a mysterious I/O error in an application that uses HTTP."

I'm puzzled by the presence of a Faraday error here, because ruby-eventsource does not use Faraday. As you can see [here](https://github.com/launchdarkly/ruby-eventsource/blob/master/lib/ld-eventsource/client.rb#L127), it always uses the `http` gem to create a client. It does have a configuration option `socket_factory` which lets you customize how sockets are created (this was provided mainly in order to support non-TCP protocols like Unix sockets), so if you are setting that parameter to something that you're getting from Faraday, then that would be the best place to look for problems. But if you're not doing that, I have no idea what's going on. I didn't think Faraday was able to modify how HTTP requests work in code that uses the `http` gem, but I don't know that library well.

**Comment by ngzax** [comment]
I appreciate you taking the time to write such a nice response.

I think because I am using Faraday to send the PUT which opens the SSE connection, it is overriding your use of the http gem? Not sure.

In any event, at this point it seems like this is clearly an issue on my side and not an issue with the lib, so I will close this out.

Thanks again!

**Comment by eli-darkly** [comment]
> I think because I am using Faraday to send the PUT which opens the SSE connection, it is overriding your use of the http gem?

I'm not sure how that's even possible, though. I mean, unless I'm missing something in the code (which I wrote, but it's been a while), there isn't any way to pass a pre-made request or connection into `SSE::Client`; it always creates its own request, using the `HTTP::Client` instance that it created (see previous link). If you could provide some sample code of how you are involving `SSE::Client.new`, that might be a clue. Or, if you want to just close this out and leave it at that, I'd still be interested to hear if you eventually find the answer.
